### ISSUE TITLE
redis in docker-compose

### ISSUE THREAD

**Issue by antoinebou13** [wyattjoh/rate-limit-redis#25]
The connection code for redis
```javascript
const RateLimitStore = require('rate-limit-redis');
const redis = require('redis');
const redisClient = redis.createClient({
	port: process.env.REDIS_PORT || undefined,
	host: process.env.REDIS_HOST || undefined,
	password: process.env.REDIS_PASSWORD || undefined,
	db: process.env.REDIS_DB || undefined,
});
new RateLimitStore({ client: redisClient, resetExpiryOnChange: true, prefix: "create" }), windowMs: 60 * 60 * 1000, max: 4, message: "You are creating too many obj. Please try again later." }
```

My docker-compose
```yml
version: "3.7"
services:
  app:
    image: app
    container_name: app
    environment:
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
      # postgres
      - POSTGRES_DB_USERNAME=opentogethertube
      - POSTGRES_DB_NAME=opentogethertube
      - POSTGRES_DB_HOST=postgres_db
      - POSTGRES_DB_PASSWORD=postgres
    ports:
      - 8080:8080
    links:
      - redis_db
      - postgres_db
    depends_on:
      - redis_db
      - postgres_db
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  redis_db:
    container_name: app_redis
    image: redis
    healthcheck:
      test: "redis-cli ping"
    expose:
      - 6379
    volumes:
      - db-data-redis:/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
```

```bash
2020-04-21 19:48:18 app info Server started on port 8080
events.js:292
throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
 Emitted 'error' event on RedisClient instance at:
     at RedisClient.on_error (/usr/app/node_modules/rate-limit-redis/node_modules/redis/index.js:406:14)
     at Socket.<anonymous> (/usr/app/node_modules/rate-limit-redis/node_modules/redis/index.js:279:14)
     at Socket.emit (events.js:315:20)
     at emitErrorNT (internal/streams/destroy.js:84:8)
     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
   errno: -111,
   code: 'ECONNREFUSED',
   syscall: 'connect',
   address: '127.0.0.1',
   port: 6379
 }
```

to enter the broken container
```yml
app:
...
command: tail -f /dev/null
...
```
if I change the default value of the host in the <app>/node_modules/rate-limit-redis/node_modules/redis/index.js line 70
cnx_options.host = options.host || 'redis_db';
then run the app it work perfectly fine
